services:
  app_proxy:
    # Umbrel injects and manages the backing app_proxy service image.
    environment:
      APP_HOST: liquid-electrs_app_1
      APP_PORT: 3006

  electrs:
    build:
      context: ${APP_DATA_DIR:-.}/electrs
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ELEMENTS_HOST: http://elements_node_1
      ELEMENTS_PORT: ${APP_ELEMENTS_NODE_RPC_PORT:-}
      ELEMENTS_USER: elements
      ELEMENTS_PASS: ${APP_ELEMENTS_RPC_PASS:-}
      ELEMENTS_CONF_DIR: /mnt/elements
      ELECTRS_LOG_LEVEL: ${ELECTRS_LOG_LEVEL:-vv}
      ELECTRS_BANNER: "Umbrel Liquid Electrs"
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${ELEMENTS_DATA_DIR}:/mnt/elements:ro
    ports:
      - "51001:50001"

  app:
    build:
      context: ${APP_DATA_DIR:-.}
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - electrs
    environment:
      PORT: "3006"
      ELEMENTS_HOST: http://elements_node_1
      ELEMENTS_PORT: ${APP_ELEMENTS_NODE_RPC_PORT:-}
      ELEMENTS_USER: elements
      ELEMENTS_PASS: ${APP_ELEMENTS_RPC_PASS:-}
      ELEMENTS_CONF_DIR: /mnt/elements
      ELECTRS_HOST: electrs
      ELECTRUM_LOCAL_SERVICE: ${DEVICE_DOMAIN_NAME:-umbrel.local}
      ELECTRUM_PORT: "51001"
    volumes:
      - ${ELEMENTS_DATA_DIR}:/mnt/elements:ro
