services:
  app_proxy:
    # Umbrel injects and manages the backing app_proxy service image.
    environment:
      APP_HOST: liquid-electrs_app_1
      APP_PORT: 3006

  electrs:
    build: ./electrs
    restart: unless-stopped
    environment:
      APP_ELEMENTS_NODE_IP: ${APP_ELEMENTS_NODE_IP:-}
      APP_ELEMENTS_RPC_PORT: ${APP_ELEMENTS_RPC_PORT:-}
      APP_ELEMENTS_RPC_USER: ${APP_ELEMENTS_RPC_USER:-}
      APP_ELEMENTS_RPC_PASS: ${APP_ELEMENTS_RPC_PASS:-}
      ELECTRS_LOG_LEVEL: ${ELECTRS_LOG_LEVEL:-vv}
      ELECTRS_BANNER: "Umbrel Liquid Electrs"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    ports:
      - "51001:50001"

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - electrs
    environment:
      PORT: "3006"
      APP_ELEMENTS_NODE_IP: ${APP_ELEMENTS_NODE_IP:-}
      APP_ELEMENTS_RPC_PORT: ${APP_ELEMENTS_RPC_PORT:-}
      APP_ELEMENTS_RPC_USER: ${APP_ELEMENTS_RPC_USER:-}
      APP_ELEMENTS_RPC_PASS: ${APP_ELEMENTS_RPC_PASS:-}
      ELECTRS_HOST: electrs
      ELECTRUM_LOCAL_SERVICE: ${DEVICE_DOMAIN_NAME:-umbrel.local}
      ELECTRUM_PORT: "51001"
